key: 62mr84kg7qezhvs49jxgw6ga
secret: QX2XpvQt45
userid: T1DYU5R3YlS5BDYADT.FHLCsh8WrGtlZnH0sSXeEqEX4M-
oauth_token: BQAJAAEDEMrBn6LSAGNnqHs0IFIr4XUwy5V4A9VTtDTJ9uRjwX2T-2hfd0brWHXK0n3ddQiEZ3Za4FyCvZ5uL_Dp0fEEIhDU
oauth_token_secret: tyne9Ban92ru